ci: add github actions (#4)
* ci: add actions (copied from my legacyplusplus)

* fix: use dev/actions instead of main branch temporarily

* fix: install latest gcc, clang

* fix: specify version

* feat: add cmake install target

* feat: use parallel build

* feat: hopefully use proper exec name on mac? update actions script to install gcc, clang on macos.

* fix: do not attempt to install gcc nor clang on macos

Run egor-tensin/setup-clang@v1
Run New-Variable os -Value 'macOS' -Option Constant
Exception: /Users/runner/work/_temp/559efd82-2644-49b2-85bd-f86b954c04cc.ps1:128
Line |
 128 |      throw "Sorry, installing Clang is unsupported on $os"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Sorry, installing Clang is unsupported on macOS
Error: Process completed with exit code 1.

* fix: attempt to properly install clang

* fix: specify clang version

* fix: force cpp20 for msft_proxy4

* fix: another attempt to fix macos building

* fix: another attempt at it

* fix: please just work

* fix: I should have just read guide that shows up after installing llvm@22

* fix: create clang++-22 symlink

* fix: ugh forgor to add \

* fix: set CC, CXX

* fix: what?

* fix: oh wait there's $GITHUB_ENV

* fix: use $GITHUB_PATH

* chore: use bio-cpp20, update to macos-26-intel

* chore: install latest gcc on macos

* feat: more macos garbage

* fix: add bundle destination

* fix: set temp exec path until I fix it tomorrow

* ci: remove windows from list (as it won't build for a while)